/**
 * @packageDocumentation
 * @module api.functional.food
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as recommend from "./recommend";
export * as analyze from "./analyze";
