/**
 * @packageDocumentation
 * @module api.functional.food
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as evaluate from "./evaluate";
export * as categories from "./categories";
export * as weather_conditions from "./weather_conditions";
export * as evaluate_summary from "./evaluate_summary";
export * as recommend from "./recommend";
export * as analyze from "./analyze";
