/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as chat from "./chat";
export * as weather from "./weather";
export * as food from "./food";
export * as restaurant from "./restaurant";
